### ISSUE TITLE
Does not work in static hosting or Github Pages

### ISSUE THREAD

**Issue by infoyard** [artemsheludko/galada#1]
I love this theme. But it does not work in static hosting (netlify) or Github pages, is that because of the Loading page? It gets stuck in that page. Can you help me with that?

You can verify by checking out infoyard.github.io and the code at https://github.com/infoyard/infoyard.github.io

**Comment by artemsheludko** [comment]
@infoyard Hello, I think the problem is in the **config.yml** file. If you use **netlify** as a hosting, try to do as in the example below

![screenshot-bitbucket org-2018 12 30-14-59-46](https://user-images.githubusercontent.com/22279513/50547542-19b34800-0c44-11e9-8557-b6b8668296e1.png)
