### ISSUE TITLE
is it possible to make another tab that includes some other posts? 

### ISSUE THREAD

**Issue by JiaxuanZhao** [artemsheludko/galada#2]
Hi,

First of all, thank you for this web, I really like it. May I ask you how to make another tab that includes some other posts? For example, right now we have a home tab that includes many posts. But I want to make another table, let's call it "life", that includes some other posts. I am a beginner in jekyll and had a hard time to figure it out. Can you please give me some helps? 

Thank you.

**Comment by artemsheludko** [comment]
@JiaxuanZhao Hi, it will be difficult for me to explain in a few sentences how it works. You most likely need to figure out how to create collections and categories to extend the functionality of your blog. Best regards
