### ISSUE TITLE
Home Page not showing Ionicons Icons

### ISSUE THREAD

**Issue by techlanka** [artemsheludko/galada#3]
my blog does not show the Ionicons Icons on the Home Page, but for other pages and post links its fine.
![1](https://user-images.githubusercontent.com/40539500/51885534-04455100-239d-11e9-8a2e-39a41939dc39.JPG)

**Comment by techlanka** [comment]
> my blog does not show the Ionicons Icons on the Home Page, but for other pages and post links its fine.
> ![1](https://user-images.githubusercontent.com/40539500/51885534-04455100-239d-11e9-8a2e-39a41939dc39.JPG)

After added a custom URL it got fixed, still i wonder why it didnt work with github.io

**Comment by artemsheludko** [comment]
#6 Problem with icons mappings resolved
