### ISSUE TITLE
Icons are not accessible after navigating to the 'Older Posts' Section

### ISSUE THREAD

**Issue by mrT4ntr4** [artemsheludko/galada#6]
![ss1](https://user-images.githubusercontent.com/46223734/55349820-44799a80-54d8-11e9-941a-7121084f1553.png)
![ss2](https://user-images.githubusercontent.com/46223734/55349838-4cd1d580-54d8-11e9-97c6-1b3e30ccdf8e.png)

## I think there is something to do with baseurl.. Could you plz check it  

![image](https://user-images.githubusercontent.com/46223734/55350024-b9e56b00-54d8-11e9-964b-dc82d2d2674b.png)

**Comment by artemsheludko** [comment]
@mrT4ntr4 Possible error in `baseurl`. It's hard to say for sure without seeing your `_config.yml ` settings.

**Comment by mrT4ntr4** [comment]
@artemsheludko 
**I was talking about the demo site provided in the readme!!**
![IMG_20190520_164156](https://user-images.githubusercontent.com/46223734/58017595-38947700-7b1e-11e9-9c05-28eed5eb795d.jpg)
![IMG_20190520_164130](https://user-images.githubusercontent.com/46223734/58017597-39c5a400-7b1e-11e9-9c83-ccf21b036fd9.jpg)

**Comment by shekhartz** [comment]
Facing similar issues

**Comment by artemsheludko** [comment]
@mrT4ntr4 @h-shekhar 

It is interesting, but I don’t have this error. Do you change `baseurl` to yours?

![Screen Shot 2019-05-21 at 5 09 10 PM](https://user-images.githubusercontent.com/22279513/58103600-e9b51300-7beb-11e9-95dd-2078c086fffe.png)

**Comment by mrT4ntr4** [comment]
### @artemsheludko I am talking about the Older Posts Section. You have shown the Screenshot of the posts which are newer.

**Comment by artemsheludko** [comment]
@mrT4ntr4 @h-shekhar 

The problem is solved by connecting the font in the head.

**Comment by mrT4ntr4** [comment]
@artemsheludko Thanks for resolving the issue!!
